//! Minimal bench mirroring `crates/kornia-cubecl/examples/bench_min.rs` — same
//! sizes, same seed, same 10rep/3warmup median methodology — so the numbers
//! produced here compare directly to the cubecl prototype on the same GPU.
//!
//! Arms per size:
//!   1. `fast_image_resize` CPU baseline (x86 AVX2 path on this box)
//!   2. cuda-oxide kernel-only (pre-uploaded buffers + pre-loaded module,
//!      times only `cuda_launch!` + `stream.synchronize()`)
//!   3. cuda-oxide end-to-end (fresh upload + launch + download per rep)

use cuda_core::{CudaContext, DeviceBuffer, LaunchConfig};
use cuda_host::cuda_launch;
// Glob import is necessary so the `__resize_bilinear_u8_rgb_CudaKernel` marker
// struct (generated by `#[kernel]` in the lib) is in scope — `cuda_launch!`
// looks it up by bare name in the current module.
use kornia_cuda_oxide::*;
use kornia_cuda_oxide::weights::{compute_axis_weights, split_weights};
use kornia_image::{Image, ImageSize};
use kornia_imgproc::{interpolation::InterpolationMode, resize};
use kornia_tensor::CpuAllocator;
use rand::{RngCore, SeedableRng, rngs::StdRng};
use std::time::Instant;

// (src_w, src_h, dst_w, dst_h) — same sweep as kornia-cubecl bench_min
const SIZES: &[(u32, u32, u32, u32)] = &[
    (512, 256, 256, 128),
    (1024, 512, 512, 256),
    (2048, 1024, 1024, 512),
    (4096, 2048, 2048, 1024),
    (8192, 4096, 4096, 2048),
    (1920, 1080, 960, 540),
];
const REPS: usize = 10;
const WARMUP: usize = 3;

fn make_image_bytes(w: u32, h: u32) -> Vec<u8> {
    let mut rng = StdRng::seed_from_u64(0xC0FFEE);
    let mut buf = vec![0u8; (w * h * 3) as usize];
    rng.fill_bytes(&mut buf);
    buf
}

fn stats(mut samples: Vec<f64>) -> (f64, f64, f64) {
    samples.sort_by(|a, b| a.partial_cmp(b).unwrap());
    let min = samples[0];
    let med = samples[samples.len() / 2];
    let mean = samples.iter().sum::<f64>() / samples.len() as f64;
    (min, med, mean)
}

fn fmt_us(s: f64) -> String {
    format!("{:>9.1}", s * 1e6)
}

fn fmt_mpix(dst_pix: u64, s: f64) -> String {
    format!("{:>7.1}", (dst_pix as f64) / s / 1e6)
}

fn main() {
    let ctx = CudaContext::new(0).expect("Failed to create CUDA context");
    let ptx_path = format!("{}/kornia_cuda_oxide.ptx", env!("CARGO_MANIFEST_DIR"));
    let module = ctx
        .load_module_from_file(&ptx_path)
        .expect("load_module_from_file");

    println!("\n# Bilinear u8 RGB 2x downscale — fast_image_resize CPU vs cuda-oxide (GTX 1650, sm_75)");
    println!("# Reps = {REPS} (with {WARMUP} warmup), reporting min/median/mean μs and Mpix/s (median).");
    println!(
        "# PTX target: $(grep '^\\.target' {ptx_path} | head -1)  — pre-loaded once, reused across reps.\n"
    );
    println!(
        "{:<22}{:<26}{:>11}{:>11}{:>11}{:>10}",
        "src→dst", "arm", "min(μs)", "med(μs)", "mean(μs)", "Mpix/s"
    );
    println!("{}", "-".repeat(91));

    for &(src_w, src_h, dst_w, dst_h) in SIZES {
        let dst_pix = (dst_w as u64) * (dst_h as u64);
        let id = format!("{src_w}x{src_h}→{dst_w}x{dst_h}");
        let src_bytes = make_image_bytes(src_w, src_h);

        // ===== CPU baseline (fast_image_resize) =====
        let src_img = Image::<u8, 3, _>::new(
            ImageSize { width: src_w as usize, height: src_h as usize },
            src_bytes.clone(),
            CpuAllocator,
        )
        .unwrap();
        let mut dst_cpu = Image::<u8, 3, _>::from_size_val(
            ImageSize { width: dst_w as usize, height: dst_h as usize },
            0,
            CpuAllocator,
        )
        .unwrap();
        for _ in 0..WARMUP {
            resize::resize_fast_rgb(&src_img, &mut dst_cpu, InterpolationMode::Bilinear).unwrap();
        }
        let mut s = Vec::with_capacity(REPS);
        for _ in 0..REPS {
            let t = Instant::now();
            resize::resize_fast_rgb(&src_img, &mut dst_cpu, InterpolationMode::Bilinear).unwrap();
            s.push(t.elapsed().as_secs_f64());
        }
        let (mn, md, mu) = stats(s);
        println!(
            "{:<22}{:<26}{}{}{}{}",
            id,
            "fast_image_resize",
            fmt_us(mn),
            fmt_us(md),
            fmt_us(mu),
            fmt_mpix(dst_pix, md)
        );

        // ===== cuda-oxide setup (shared between kernel-only and e2e) =====
        let stream = ctx.default_stream();

        let wx = compute_axis_weights(src_w, dst_w);
        let wy = compute_axis_weights(src_h, dst_h);
        let (wx_idx, wx_w) = split_weights(&wx);
        let (wy_idx, wy_w) = split_weights(&wy);

        // ===== cuda-oxide kernel-only =====
        // Pre-upload everything; time only kernel dispatch + sync.
        let src_dev = DeviceBuffer::from_host(&stream, &src_bytes).unwrap();
        let mut dst_dev =
            DeviceBuffer::<u8>::zeroed(&stream, (dst_w * dst_h * 3) as usize).unwrap();
        let wx_idx_dev = DeviceBuffer::from_host(&stream, &wx_idx).unwrap();
        let wx_w_dev = DeviceBuffer::from_host(&stream, &wx_w).unwrap();
        let wy_idx_dev = DeviceBuffer::from_host(&stream, &wy_idx).unwrap();
        let wy_w_dev = DeviceBuffer::from_host(&stream, &wy_w).unwrap();

        let block = (16u32, 16u32, 1u32);
        let grid = (dst_w.div_ceil(block.0), dst_h.div_ceil(block.1), 1u32);
        let cfg = LaunchConfig {
            grid_dim: grid,
            block_dim: block,
            shared_mem_bytes: 0,
        };

        for _ in 0..WARMUP {
            cuda_launch! {
                kernel: resize_bilinear_u8_rgb,
                stream: stream,
                module: module,
                config: cfg,
                args: [
                    slice(src_dev), slice_mut(dst_dev),
                    slice(wx_idx_dev), slice(wx_w_dev),
                    slice(wy_idx_dev), slice(wy_w_dev),
                    src_w, dst_w, dst_h
                ]
            }
            .unwrap();
            stream.synchronize().unwrap();
        }
        let mut s = Vec::with_capacity(REPS);
        for _ in 0..REPS {
            let t = Instant::now();
            cuda_launch! {
                kernel: resize_bilinear_u8_rgb,
                stream: stream,
                module: module,
                config: cfg,
                args: [
                    slice(src_dev), slice_mut(dst_dev),
                    slice(wx_idx_dev), slice(wx_w_dev),
                    slice(wy_idx_dev), slice(wy_w_dev),
                    src_w, dst_w, dst_h
                ]
            }
            .unwrap();
            stream.synchronize().unwrap();
            s.push(t.elapsed().as_secs_f64());
        }
        let (mn, md, mu) = stats(s);
        println!(
            "{:<22}{:<26}{}{}{}{}",
            "",
            "cuda_oxide_kernel",
            fmt_us(mn),
            fmt_us(md),
            fmt_us(mu),
            fmt_mpix(dst_pix, md)
        );

        // ===== cuda-oxide tiled x4 (4 dst pixels per thread) =====
        if dst_w % 4 == 0 {
            let block_x4 = (16u32, 16u32, 1u32);
            let grid_x4 = (
                (dst_w / 4).div_ceil(block_x4.0),
                dst_h.div_ceil(block_x4.1),
                1u32,
            );
            let cfg_x4 = LaunchConfig {
                grid_dim: grid_x4,
                block_dim: block_x4,
                shared_mem_bytes: 0,
            };
            for _ in 0..WARMUP {
                cuda_launch! {
                    kernel: resize_bilinear_u8_rgb_x4,
                    stream: stream,
                    module: module,
                    config: cfg_x4,
                    args: [
                        slice(src_dev), slice_mut(dst_dev),
                        slice(wx_idx_dev), slice(wx_w_dev),
                        slice(wy_idx_dev), slice(wy_w_dev),
                        src_w, dst_w, dst_h
                    ]
                }
                .unwrap();
                stream.synchronize().unwrap();
            }
            let mut s = Vec::with_capacity(REPS);
            for _ in 0..REPS {
                let t = Instant::now();
                cuda_launch! {
                    kernel: resize_bilinear_u8_rgb_x4,
                    stream: stream,
                    module: module,
                    config: cfg_x4,
                    args: [
                        slice(src_dev), slice_mut(dst_dev),
                        slice(wx_idx_dev), slice(wx_w_dev),
                        slice(wy_idx_dev), slice(wy_w_dev),
                        src_w, dst_w, dst_h
                    ]
                }
                .unwrap();
                stream.synchronize().unwrap();
                s.push(t.elapsed().as_secs_f64());
            }
            let (mn, md, mu) = stats(s);
            println!(
                "{:<22}{:<26}{}{}{}{}",
                "",
                "cuda_oxide_kernel_x4",
                fmt_us(mn),
                fmt_us(md),
                fmt_us(mu),
                fmt_mpix(dst_pix, md)
            );
        }

        // ===== cuda-oxide tiled x16 (16 dst pixels per thread) =====
        if dst_w % 16 == 0 {
            let block_x16 = (16u32, 16u32, 1u32);
            let grid_x16 = (
                (dst_w / 16).div_ceil(block_x16.0),
                dst_h.div_ceil(block_x16.1),
                1u32,
            );
            let cfg_x16 = LaunchConfig {
                grid_dim: grid_x16,
                block_dim: block_x16,
                shared_mem_bytes: 0,
            };
            for _ in 0..WARMUP {
                cuda_launch! {
                    kernel: resize_bilinear_u8_rgb_x16,
                    stream: stream,
                    module: module,
                    config: cfg_x16,
                    args: [
                        slice(src_dev), slice_mut(dst_dev),
                        slice(wx_idx_dev), slice(wx_w_dev),
                        slice(wy_idx_dev), slice(wy_w_dev),
                        src_w, dst_w, dst_h
                    ]
                }
                .unwrap();
                stream.synchronize().unwrap();
            }
            let mut s = Vec::with_capacity(REPS);
            for _ in 0..REPS {
                let t = Instant::now();
                cuda_launch! {
                    kernel: resize_bilinear_u8_rgb_x16,
                    stream: stream,
                    module: module,
                    config: cfg_x16,
                    args: [
                        slice(src_dev), slice_mut(dst_dev),
                        slice(wx_idx_dev), slice(wx_w_dev),
                        slice(wy_idx_dev), slice(wy_w_dev),
                        src_w, dst_w, dst_h
                    ]
                }
                .unwrap();
                stream.synchronize().unwrap();
                s.push(t.elapsed().as_secs_f64());
            }
            let (mn, md, mu) = stats(s);
            println!(
                "{:<22}{:<26}{}{}{}{}",
                "",
                "cuda_oxide_kernel_x16",
                fmt_us(mn),
                fmt_us(md),
                fmt_us(mu),
                fmt_mpix(dst_pix, md)
            );
        }

        // ===== cuda-oxide end-to-end (fresh upload+launch+download per rep) =====
        for _ in 0..WARMUP {
            let s = DeviceBuffer::from_host(&stream, &src_bytes).unwrap();
            let mut d = DeviceBuffer::<u8>::zeroed(&stream, (dst_w * dst_h * 3) as usize).unwrap();
            let wx_i = DeviceBuffer::from_host(&stream, &wx_idx).unwrap();
            let wx_v = DeviceBuffer::from_host(&stream, &wx_w).unwrap();
            let wy_i = DeviceBuffer::from_host(&stream, &wy_idx).unwrap();
            let wy_v = DeviceBuffer::from_host(&stream, &wy_w).unwrap();
            cuda_launch! {
                kernel: resize_bilinear_u8_rgb,
                stream: stream,
                module: module,
                config: cfg,
                args: [slice(s), slice_mut(d), slice(wx_i), slice(wx_v), slice(wy_i), slice(wy_v), src_w, dst_w, dst_h]
            }
            .unwrap();
            let _ = d.to_host_vec(&stream).unwrap();
        }
        let mut samples = Vec::with_capacity(REPS);
        for _ in 0..REPS {
            let t = Instant::now();
            let s = DeviceBuffer::from_host(&stream, &src_bytes).unwrap();
            let mut d = DeviceBuffer::<u8>::zeroed(&stream, (dst_w * dst_h * 3) as usize).unwrap();
            let wx_i = DeviceBuffer::from_host(&stream, &wx_idx).unwrap();
            let wx_v = DeviceBuffer::from_host(&stream, &wx_w).unwrap();
            let wy_i = DeviceBuffer::from_host(&stream, &wy_idx).unwrap();
            let wy_v = DeviceBuffer::from_host(&stream, &wy_w).unwrap();
            cuda_launch! {
                kernel: resize_bilinear_u8_rgb,
                stream: stream,
                module: module,
                config: cfg,
                args: [slice(s), slice_mut(d), slice(wx_i), slice(wx_v), slice(wy_i), slice(wy_v), src_w, dst_w, dst_h]
            }
            .unwrap();
            let _ = d.to_host_vec(&stream).unwrap();
            samples.push(t.elapsed().as_secs_f64());
        }
        let (mn, md, mu) = stats(samples);
        println!(
            "{:<22}{:<26}{}{}{}{}",
            "",
            "cuda_oxide_e2e",
            fmt_us(mn),
            fmt_us(md),
            fmt_us(mu),
            fmt_mpix(dst_pix, md)
        );

        println!();
    }
}
